# Site settings
title: Shailesh's Math classes
email: shailesh.earth@gmail.com
description: "Learn mathematics conceptually"
baseurl: file:///home/manishearth/Git/freelancer-theme/build/
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/shaileshgoregaokar
  - title: facebook
    url: https://www.facebook.com/pages/Math-With-Shailesh/1574338889462413
  - title: envelope
    url: mailto:math.shailesh@gmail.com

  
# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
